### PR TITLE
Added support for Web Api

### PR DESCRIPTION
**Pull request by TrevorPilley**
This is not complete, however I haven't had time to figure out the remaining bits (see the TODOs) so it's up for grabs if you are interested in adding support for WebApi.

It is based upon the MVC extension but built for WebApi.Core so it is suitable in both WebHost (IIS) and SelfHost (OWIN), I've included an example app for using it in a self hosted environment with instructions of how to wire it all up.

### CODE REVIEW

**Comment by TrevorPilley** [comment]
Do you have any interest in this at all or shall I just close the PR?

**Comment by yellis** [comment]
I am not planning on doing anything with it. If you complete it, I will be
happy to look it over and merge.

**Comment by YJingLee** [comment]
+1 support for Web Api

**Comment by gdoron** [comment]
@YJingLee In ASP.Net Core MVC&WebAPI are the same thing, so... just wait for Core support.

**Pull request closed without merging**
