### PR TITLE
'profile' tag helper enhancement

### PR DESCRIPTION
**Pull request by StuffOfInterest**
Removes 'profile' tag from HTML page output and doesn't wrap code in 'using' statement when MiniProfiler is inactive to boost rendering performance.

Sorry for the five commits in the pull request.  Had issues resyncing my development clone.  I guess squashing the request will take care of the noise.

As I'm implementing MiniProfiler in a project at work I'm running into things like this that I'm trying to correct.  I've been using MiniProfiler for over seven years now, so glad to give a little bit back.

### CODE REVIEW

**Comment by NickCraver** [comment]
I'm not sure I follow the changes here, can you help me understand? The only net change I see is the `using()` overall, but that's already a `using (null)` when MiniProfiler is off (this is a global optimization, and doesn't double-check `.Current` - that's why `.Step()` is an extension that handles nulls). That specific change isn't necessary...and should really be less optimal than current.

The `<profile>` tag in the page though: I don't see that in the commit. Is this an issue, is it being rendered in the page somewhere? If that's the case: yes, need to address that for sure.

**Comment by StuffOfInterest** [comment]
Setting `output.TagName = null;` causes the `<profile>` tag to be removed from the output HTML.  If it wasn't for all the using() related code it would have been a one liner.

As for the using change, I knew that the result was going to be a `using(null)` when MiniProfiler is disabled, but I wasn't sure how that would compile below the surface.  Is the wrapping code for a using with no lock object as performant as doing the null check?  If so, then there is no need for that part of the change. I was just hoping to minimize the impact of the MiniProfiler code when it is disabled.

**Comment by NickCraver** [comment]
Ahhh, missed the line! Indeed that change is necessary (thanks for the catch!)

The `using` changes aren't necessary though - can you please move `output.TagName = null;` to top of the method and remove the `using` `if`/`else` changes? Then happy to merge in :)

**Comment by StuffOfInterest** [comment]
Done.

Not sure I'll ever be used to how git updates pull requests automatically with further checkins to a branch.

**Comment by NickCraver** [comment]
Merged in, thanks for the contribution here! I completely missed that was happening :)

**Pull request merged**
