### PR TITLE
Update AspDotNetCore.md to add Memory Cache

### PR DESCRIPTION
**Pull request by ceemafour**
Add required step to add services.AddMemoryCache() which is essential for MiniProfiler to work in .Net Core

### CODE REVIEW

**Comment by NickCraver** [comment]
@ceemafour This should not be needed since 4.2.1 (see release notes: https://miniprofiler.com/dotnet/Releases) - are you still encountering a case where it is?

**Comment by ceemafour** [comment]
Yes it’s still happening. Downloaded the nuget 4.2.1 today and ran into this issue.

**Comment by NickCraver** [comment]
@ceemafour we should look at your config - what error is happening? Note from the examples - it should not be needed: https://github.com/MiniProfiler/dotnet/blob/main/samples/Samples.AspNetCore3/Startup.cs#L34 - they run just fine. I'd like too understand what's different about your scenario that it's not behaving, rather than adjusting the docs. There's a bug here if you still need this.

**Comment by NickCraver** [comment]
Closing this out to cleanup!

**Pull request closed without merging**
