### PR TITLE
plugin for Entity Framework Classic 7

### PR DESCRIPTION
**Pull request by JendaPerl**
I've just made a copy of the Miniprofiler.EF6 as Miniprofiler.EFC7 and tweaked it to reference and use the https://entityframework-classic.net/ instead of the official EF 6. Not sure what needs to be done to get a nuget package, but the obtained MiniProfiler.EFC7.dll does work with the current Miniprofiler and EFC 7.1.9.

The initialization just needs to be changed to

StackExchange.Profiling.EntityFrameworkClassic7.MiniProfilerEFC7.Initialize();
in place of
StackExchange.Profiling.EntityFramework6.MiniProfilerEF6.Initialize();

I would very much appreciate if anyone could finish whatever needs to be done to end up with a nuget.

### CODE REVIEW

**Comment by JendaPerl** [comment]
What the what?

no matching manifest for windows/amd64 10.0.17134 in the manifest list entries
##[warning]Docker pull failed with exit code 1, back off 3.444 seconds before retry.
##[command]C:\Program Files\Docker\docker.EXE pull redis
Using default tag: latest
no matching manifest for windows/amd64 10.0.17134 in the manifest list entries
latest: Pulling from library/redis
##[warning]Docker pull failed with exit code 1, back off 3.905 seconds before retry.
##[command]C:\Program Files\Docker\docker.EXE pull redis
Using default tag: latest
no matching manifest for windows/amd64 10.0.17134 in the manifest list entries
latest: Pulling from library/redis
##[error]Docker pull failed with exit code 1

It seems setting up the tests failed before anything I did came to play.

**Comment by NickCraver** [comment]
I was getting `netcoreapp3.0` initial bits working (which conflicted) - going to try and update some of these PRs to work :)

**Comment by JendaPerl** [comment]
I noticed that I've made a typo in the readme. I suggest install of Miniprofiler.EFC76 instead of Miniprofiler.EFC7. Could you fix this or change it to whatever you decide to call the package?
I think that's easier than going through the exercise of forking and creating a pull request for a one character change. :-)

Thanks!

**Comment by NickCraver** [comment]
Done in c3c66d3 :)

**Pull request merged**
