### PR TITLE
Add Support for Azure DevOps Builds

### PR DESCRIPTION
**Pull request by GuruCharan94**
# Add Support for Azure Pipelines #338 
You can see the builds at https://dev.azure.com/agileguru/MiniProfiler/_build?definitionId=48&_a=summary

The build is triggered for every push to master and PR's targeting master.
The build process spins up 
- Redis
- MySQL
- PostgreSQL
- MongoDB 
- SQL Server (LocalDB)

## Build Artifacts
The Build publishes Build Artifacts (not to be confused with Azure Artifacts) only for CI Builds (in master) and not for PR's.
artifacts

 
## Tests 
4 0 151 gurucharan94 dotnet

**12 SQL Server Tests are skipped with below message**
`Couldn't test against: StackExchange.Profiling.Storage.SqlServerStorage\nThe type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
`

### CODE REVIEW

**Comment by GuruCharan94** [comment]
@NickCraver, thoughts ?

**Comment by NickCraver** [comment]
@GuruCharan94 sorry I've been slow over the holidays - this looks awesome and I very much appreciate it. I'm going to pull in master and try to setup a build as soon as time allows!

**Comment by GuruCharan94** [comment]
Take your time.  If this works well, I can also help you with Azure DevOps builds for your other projects like Dapper etc. Just let me know.

**Comment by NickCraver** [comment]
@GuruCharan94 this works indeed! I'll worry about the MyGet publishing later, but I wanted to let you know this is live here: https://dev.azure.com/stackoverflowoss/StackOSS/_build/results?buildId=395 and I'm looking at a new announcement today: https://blogs.msdn.microsoft.com/devops/2019/01/23/using-containerized-services-in-your-pipeline/ which seems like *exactly* what we need here for more speed and simplicity. Hopefully I can poke that the next few days.

I'm just commenting here to give you an update on progress and to say thanks again for getting this major hurdle out of the way. My OSS time's very limited these days and your contributions are most appreciated <3

**Pull request merged**
