### PR TITLE
Fix #653, #659 - Fix UI to work with most recent first

### LINKED ISSUE #653: polling use first instead of last
It appears that there is an issue with the JavaScript component responsible for polling the next result on the results-index page. The page is arranged in descending order by time, with the most recent item at the top. However, the last ID used for polling is the least recent one, causing the page to continuously grow larger as it retrieves n-1 results with each polling iteration.

image

Most likely the error is here https://github.com/MiniProfiler/dotnet/blob/a009d55a19050c8b88a3ea0c357d54ad192763b5/src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts#L439C57-L439C64

it should be oldData[0]

Note even with that fix we will end up with the wrong result displayed as it will display all the new results at the bottom...

that's what we currently would see with 3 items:

```
first load
3
2
1
polling last id=1
3
2
polling last id = 2
3
polling last id = 3
polling last id = 3
polling last id = 3
```
if we use oldData[0]
this would work like that:
```
first load
3
2
1
polling last id = 3
polling last id = 3
polling last id = 3
```
but as soon as we get a new id 4 the polling will push it at the end and the page table will now display
```
3
2
1
polling last id = 3
4
```

### PR DESCRIPTION
**Pull request by RobertSmits**
Fixes both #653 and #659 by updating the UI to work with the recent-trace-first sorting introduced in #550

### CODE REVIEW

**Comment by axylophon** [comment]
@NickCraver : could you please look at this PR as the UI is currently broken...

**Comment by afuersch** [comment]
@NickCraver Is there any chance to merge this PR soon? The UI is currently broken ...

**Comment by LEIRONGHUA** [comment]
Does this PR have the latest progress?  The UI is Currently Broken, can no longer be used normally

**Review by NickCraver — APPROVED** [review]

**Comment by NickCraver** [comment]
Thanks for the fix here! This will be int he 4.5.x update.

**Pull request merged**
